name: Post RSS Feed to LinkedIn Page

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

jobs:
  post_to_linkedin:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install feedparser requests beautifulsoup4 lxml

      - name: Parse RSS feed and post to LinkedIn Page
        run: |
          . venv/bin/activate
          python parser_post_to_linkedin.py
        env:
          LINKEDIN_ACCESS_TOKEN: ${{ secrets.LINKEDIN_ACCESS_TOKEN }}
          LINKEDIN_ORG_ID: ${{ secrets.LINKEDIN_ORG_ID }}
